// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using canary.Models;

namespace canary.Migrations
{
    [DbContext(typeof(RecordContext))]
    [Migration("20190821025623_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("canary.Models.Endpoint", b =>
                {
                    b.Property<int>("EndpointId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Finished");

                    b.Property<string>("Issues");

                    b.Property<string>("Record");

                    b.HasKey("EndpointId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("canary.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FhirInfo");

                    b.Property<string>("Ije");

                    b.Property<string>("IjeInfo");

                    b.Property<string>("Json");

                    b.Property<string>("Xml");

                    b.HasKey("RecordId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("canary.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CompletedBool");

                    b.Property<DateTime>("CompletedDateTime");

                    b.Property<int>("Correct");

                    b.Property<DateTime>("Created");

                    b.Property<int>("Incorrect");

                    b.Property<string>("ReferenceRecord");

                    b.Property<string>("Results");

                    b.Property<string>("TestRecord");

                    b.Property<int>("Total");

                    b.Property<string>("Type");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
