// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using canary.Models;

namespace canary.Migrations
{
    [DbContext(typeof(RecordContext))]
    [Migration("20200718201840_AddMessagesTable")]
    partial class AddMessagesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("canary.Models.Endpoint", b =>
                {
                    b.Property<int>("EndpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issues")
                        .HasColumnType("TEXT");

                    b.Property<string>("Record")
                        .HasColumnType("TEXT");

                    b.HasKey("EndpointId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("canary.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("canary.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FhirInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ije")
                        .HasColumnType("TEXT");

                    b.Property<string>("IjeInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("canary.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompletedBool")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Correct")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Incorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceRecord")
                        .HasColumnType("TEXT");

                    b.Property<string>("Results")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TestMessageMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestRecord")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("TestId");

                    b.HasIndex("TestMessageMessageId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("canary.Models.Test", b =>
                {
                    b.HasOne("canary.Models.Message", "TestMessage")
                        .WithMany()
                        .HasForeignKey("TestMessageMessageId");
                });
#pragma warning restore 612, 618
        }
    }
}
