name: Trigger auto deployment for canary-v4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/canary-v4-AutoDeployTrigger-c1d487da-889f-4f5d-bb2d-7739826c6c68.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CANARYV4_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CANARYV4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CANARYV4_REGISTRY_PASSWORD }}
          containerAppName: canary-v4
          resourceGroup: nchs-nvss-prd-moderate-canary-rg
          imageToBuild: ghcr.io/canary:${{ github.sha }}
          
            

     

