name: Deploy reference implementation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CTENVSSCANARY_AZURE_CREDENTIALS }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ctenvss20221223092705.azurecr.io
          registryUsername: ${{ secrets.CTENVSSCANARY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CTENVSSCANARY_REGISTRY_PASSWORD }}
          containerAppName: nvss-canary-staging
          resourceGroup: CTE_NVSS
          imageToBuild: ctenvss20221223092705.azurecr.io/nvss-canary-staging:${{ github.sha }}
          