name: Create new tag on version updates

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  parse-commit:
    runs-on: ubuntu-latest
    outputs:
      subject: ${{ steps.commit-subject.outputs.subject }}
    steps:
      - uses: actions/checkout@v3
      - name: Get commit subject
        id: commit-subject
        run: |
          echo "subject=$(git log -n 1 --pretty=%s)" >> $GITHUB_OUTPUT
  tag-new-version:
    runs-on: ubuntu-latest
    needs: parse-commit
    if: startsWith(needs.parse-commit.outputs.subject, 'chore(release):')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Setup Versionize
        run: |
          dotnet tool install --global Versionize
      - name: Generate changes since last tag
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:%s > TAGCHANGES
      - name: Tag current version 
        run: |
          git tag -a $(versionize inspect) -f -F TAGCHANGES
      - name: Push new tag
        run: |
          git push --tags origin master